project:
  type: website
  output-dir: docs
  resources: 
    - "*.pdf"


website:
  title: "Monserrat Olavarria Balmaceda"
  navbar:
    right:
      - text: Dischi
        href: dischi.qmd
      - text: Spettacoli
        href: spettacoli.qmd
      - text: Corsi
        href: corsi.qmd
      - text: Chi sono
        href: about.qmd    
      - text: Contatti
        href: contact.qmd
      - icon: youtube
        href: https://www.youtube.com/channel/UCMQJkzvobU3ZikrzYaY3x7w/featured/
      - icon: messenger
        href: https://m.me/avenidamerica/
      - icon: facebook
        href: https://www.facebook.com/avenidamerica/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

lang: it

#execute:
#  freeze: true  # never re-render during project render
#  freeze: auto  # re-render only when source changes
